# Generated by Django 5.2.13 on 2026-04-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField()),
                ('client_phone', models.CharField(max_length=50)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('site_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('profile_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profilesystem')),
            ],
        ),
        migrations.CreateModel(
            name='WindowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='e.g. W01, D02', max_length=50)),
                ('width', models.FloatField(help_text='in mm')),
                ('height', models.FloatField(help_text='in mm')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('has_mesh', models.BooleanField(default=False)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('computed', models.BooleanField(default=False)),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.finish')),
                ('glass_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.glasstype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='projects.project')),
                ('typology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.windowtypology')),
            ],
        ),
        migrations.CreateModel(
            name='ComputedCutPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=255)),
                ('length', models.FloatField(help_text='mm')),
                ('quantity', models.IntegerField()),
                ('total_length', models.FloatField(help_text='length * quantity * window.quantity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.profile')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_pieces', to='projects.windowentry')),
            ],
        ),
    ]
