# Generated by Codex on 2026-04-18

from django.db import migrations


def map_legacy_statuses(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    status_mapping = {
        'draft': 'pending',
        'quoted': 'accepted',
        'confirmed': 'accepted',
    }
    for legacy_status, new_status in status_mapping.items():
        Project.objects.filter(status=legacy_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_accepted_at_project_accepted_by_and_more'),
    ]

    operations = [
        migrations.RunPython(map_legacy_statuses, migrations.RunPython.noop),
    ]
