# Generated by Django 5.2.13 on 2026-04-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=255)),
                ('quantity_formula', models.CharField(help_text='e.g., "2" or "num_panels"', max_length=255)),
                ('length_formula', models.CharField(help_text='e.g., "width - 2 * frame_deduction"', max_length=255)),
                ('deduction_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='GlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thickness', models.FloatField(help_text='mm')),
                ('cost_per_sqm', models.FloatField(help_text='INR')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('handle', 'Handle'), ('hinge', 'Hinge'), ('lock', 'Lock'), ('roller', 'Roller'), ('seal', 'Seal'), ('other', 'Other')], max_length=50)),
                ('unit', models.CharField(choices=[('per_unit', 'Per Unit'), ('per_metre', 'Per Metre'), ('per_window', 'Per Window')], max_length=50)),
                ('unit_cost', models.FloatField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('frame', 'Frame'), ('sash', 'Sash'), ('mullion', 'Mullion'), ('transom', 'Transom'), ('bead', 'Bead'), ('other', 'Other')], max_length=50)),
                ('unit_weight', models.FloatField(help_text='kg/m')),
                ('unit_cost', models.FloatField(help_text='INR per mm')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(choices=[('aluminium', 'Aluminium'), ('upvc', 'uPVC'), ('wood', 'Wood'), ('steel', 'Steel')], max_length=50)),
                ('standard_bar_length', models.FloatField(default=6000)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindowTypology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sliding', 'Sliding'), ('casement', 'Casement'), ('fixed', 'Fixed'), ('tilt_turn', 'Tilt & Turn'), ('awning', 'Awning'), ('door', 'Door')], max_length=50)),
                ('description', models.TextField()),
                ('diagram_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuttingRuleDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('value', models.FloatField(help_text='in mm')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='catalog.cuttingrule')),
            ],
        ),
        migrations.AddField(
            model_name='cuttingrule',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='catalog.profilesystem'),
        ),
        migrations.CreateModel(
            name='HardwareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_formula', models.CharField(help_text='e.g., "2" or "num_panels * 2"', max_length=255)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hardware')),
                ('typology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='catalog.windowtypology')),
            ],
        ),
        migrations.AddField(
            model_name='cuttingrule',
            name='typology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_rules', to='catalog.windowtypology'),
        ),
    ]
