# Generated by Django 5.2.13 on 2026-04-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimisationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_bars_used', models.IntegerField(default=0)),
                ('total_waste_mm', models.FloatField(default=0.0)),
                ('overall_efficiency', models.FloatField(default=0.0)),
                ('result_data', models.JSONField(default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimisation_result', to='projects.project')),
            ],
        ),
    ]
